version: 2.1

executors:
  docker:
    docker:
      - image: circleci/golang:1.9

jobs:
  cx-scan:
    docker:
      - image: docker.io/checkmarxts/cxflow
    steps:
      - checkout
      - run:
          name: "Checkmarx Scan"
          command: |
            echo ${CX_FLOW_CONFIG} | base64 -d > application.yml
            ${CX_FLOW_EXE} \
            --scan \
            --cx-team="\CxServer\SP\Checkmarx" \
            --cx-project="${CIRCLE_PROJECT_REPONAME}" \
            --app="${CIRCLE_PROJECT_REPONAME}" \
            --f=. \
            --cx-flow.break-build=false 
      - store_artifacts:
          path: cx.json

workflows:
  version: 2
  build_deploy:
    jobs:
      - cx-scan:
          filters:
            branches:
              only: master
