version: 2.1

orbs:
  cxflow: checkmarx-ts/cxflow@1.0.1

jobs:
  build:
    executor: cxflow/default
    steps:
      - checkout
      - cxflow/scan:
          team: "\\CxServer\\SP\\Checkmarx"
          preset: "Checkmarx Express"
          report-file: checkmarx.json
      - store_artifacts:
          path: checkmarx.json
          
workflows:
  version: 2
  build_deploy:
    jobs:
      - cx-scan:
          filters:
            branches:
              only: master
