version: 2.1

orbs:
  cxflow: checkmarx-ts/cxflow@dev:alpha
          
workflows:
  version: 2
  sast-scan:
    jobs:
      - cxflow/results:
          project: "Riches"
          team: "\\CxServer\\SP\\Checkmarx"    
#      - cxflow/scan:
#          team: "\\CxServer\\SP\\Checkmarx"
#          preset: "Checkmarx Express"
#          report-file: vulns.json
#          filters:
#            branches:
#              only:
#                - master
