version: 2.1

executors:
  docker:
    docker:
      - image: circleci/golang:1.9

jobs:
  cx-scan:
    docker:
      - image: docker.io/checkmarxts/cxflow
    steps:
      - checkout
      - run:
          name: "Checkmarx Scan"
          command: |
            echo ${CX_FLOW_CONFIG} | base64 -d > application.yml
            cat application.yml
            ${CX_FLOW_EXE} --scan --cx-team="\CxServer\SP\Checkmarx" --cx-project="JavaVulnerableLab" --f=. 
            mv *.zip cx.zip
      - store_artifacts:
          path: cx.*

workflows:
  version: 2
  build_deploy:
    jobs:
      - cx-scan:
          filters:
            branches:
              only: master
