version: 2.1

orbs:
  cxflow: checkmarx-ts/cxflow@1.0.3

jobs:
  cx-scan:
    executor: cxflow/default
    steps:
      - checkout
      - cxflow/scan:
          team: "\\CxServer\\SP\\Checkmarx"
          preset: "Checkmarx Express"
          report-file: checkmarx.json
      - store_artifacts:
          path: checkmarx.json
  cx-results:
    executor: cxflow/default
    steps:
      - checkout
      - cxflow/results:
          team: "\\CxServer\\SP\\Checkmarx"
          project: "Riches"
          report-file: checkmarx-results.json
      - store_artifacts:
          path: checkmarx-results.json
          
workflows:
  version: 2
  build_deploy:
    jobs:
      - cx-scan:
          filters:
            branches:
              only: master
      - cx-results:
          filters:
            branches:
              only: master
