version: 2.1

executors:
  docker:
    docker:
      - image: circleci/golang:1.9

jobs:
  cx-scan:
    docker:
      - image: docker.io/checkmarxts/cxflow
    steps:
      - checkout
      - run: java -jar /app/cx-flow.jar --spring.config.location=./application.yml
      - store_artifacts:
          path: build/libs

workflows:
  version: 2
  build_deploy:
    jobs:
      - cx-scan:
          filters:
            branches:
              only: master
