version: 2.1

executors:
  docker:
    docker:
      - image: circleci/golang:1.9

jobs:
  cx-scan:
    docker:
      - image: docker.io/checkmarxts/cxflow
    environment:
      CX_PROJECT: JavaVulnerableLab
      CX_TEAM: \CxServer\SP\Checkmarx
    steps:
      - checkout
      - run:
          name: "Checkmarx Scan"
          command: |
            echo $MY_ENCODED_VALUE | base64 -d > application.yml
            ${CX_FLOW_EXE} --scan --cx-team="${CX_TEAM}" --cx-project="${CX_PROJECT}" --app="${CX_PROJECT}" --f=. 
            mv *.zip cx.zip
      - store_artifacts:
          path: 
            - cx.zip
            - cx.json

workflows:
  version: 2
  build_deploy:
    jobs:
      - cx-scan:
          filters:
            branches:
              only: master
